"""Add new changes

Revision ID: 2640b0af40e3
Revises: ed9785273900
Create Date: 2024-01-21 11:21:24.080977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2640b0af40e3'
down_revision: Union[str, None] = 'ed9785273900'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kalendereintraege', sa.Column('start', sa.DateTime(), nullable=True))
    op.add_column('kalendereintraege', sa.Column('ende', sa.DateTime(), nullable=True))
    op.add_column('kalendereintraege', sa.Column('allDay', sa.Boolean(), nullable=True))
    op.drop_column('kalendereintraege', 'zeitpunkt')
    op.alter_column('rechnungen', 'rechnungsbetrag',
               existing_type=sa.NUMERIC(precision=11, scale=3),
               type_=sa.Numeric(precision=11, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rechnungen', 'rechnungsbetrag',
               existing_type=sa.Numeric(precision=11, scale=2),
               type_=sa.NUMERIC(precision=11, scale=3),
               existing_nullable=True)
    op.add_column('kalendereintraege', sa.Column('zeitpunkt', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_column('kalendereintraege', 'allDay')
    op.drop_column('kalendereintraege', 'ende')
    op.drop_column('kalendereintraege', 'start')
    # ### end Alembic commands ###