"""Add new changes

Revision ID: 339e433039f1
Revises: 4c7454ebec26
Create Date: 2024-02-05 16:25:15.128060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339e433039f1'
down_revision: Union[str, None] = '4c7454ebec26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('angebote', 'angebotsstatus')
    op.add_column('nutzer', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutzer', 'is_active')
    op.add_column('angebote', sa.Column('angebotsstatus', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###