"""Add new changes

Revision ID: 4c7454ebec26
Revises: 19f2465a31a1
Create Date: 2024-01-29 23:45:48.041705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c7454ebec26'
down_revision: Union[str, None] = '19f2465a31a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('nachricht_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('empfaenger_id', sa.Integer(), nullable=True),
    sa.Column('nachricht_inhalt', sa.String(), nullable=False),
    sa.Column('timestamp', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['empfaenger_id'], ['nutzer.user_id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['nutzer.user_id'], ),
    sa.PrimaryKeyConstraint('nachricht_id')
    )
    op.create_index(op.f('ix_chat_messages_nachricht_id'), 'chat_messages', ['nachricht_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_nachricht_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    # ### end Alembic commands ###