"""Add new changes

Revision ID: a3857cab1d12
Revises: cf04badbe5a8
Create Date: 2024-01-19 16:19:44.262273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3857cab1d12'
down_revision: Union[str, None] = 'cf04badbe5a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rechnungen', sa.Column('zahlungsstatus', sa.Enum('Bezahlt', 'Offen', 'Teilweise_Bezahlt', 'Storniert', 'Überfällig', name='zahlungsstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rechnungen', 'zahlungsstatus')
    # ### end Alembic commands ###