"""Add new changes

Revision ID: c51ca99baf27
Revises: 40be302dae9e
Create Date: 2024-01-21 10:48:00.935227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51ca99baf27'
down_revision: Union[str, None] = '40be302dae9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rechnungen', sa.Column('rechnungsperiode_start', sa.Date(), nullable=True))
    op.add_column('rechnungen', sa.Column('rechnungsperiode_ende', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rechnungen', 'rechnungsperiode_ende')
    op.drop_column('rechnungen', 'rechnungsperiode_start')
    # ### end Alembic commands ###