"""Add new changes

Revision ID: cf04badbe5a8
Revises: 80781dcf2931
Create Date: 2024-01-19 15:51:48.623693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf04badbe5a8'
down_revision: Union[str, None] = '80781dcf2931'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energieeffizienzmassnahmen', sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('rechnungen', sa.Column('empfaenger_id', sa.Integer(), nullable=True))
    op.add_column('rechnungen', sa.Column('steller_id', sa.Integer(), nullable=True))
    op.drop_constraint('rechnungen_user_id_fkey', 'rechnungen', type_='foreignkey')
    op.create_foreign_key(None, 'rechnungen', 'nutzer', ['empfaenger_id'], ['user_id'])
    op.create_foreign_key(None, 'rechnungen', 'nutzer', ['steller_id'], ['user_id'])
    op.drop_column('rechnungen', 'user_id')
    op.drop_column('rechnungen', 'zeitraum')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rechnungen', sa.Column('zeitraum', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('rechnungen', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rechnungen', type_='foreignkey')
    op.drop_constraint(None, 'rechnungen', type_='foreignkey')
    op.create_foreign_key('rechnungen_user_id_fkey', 'rechnungen', 'nutzer', ['user_id'], ['user_id'])
    op.drop_column('rechnungen', 'steller_id')
    op.drop_column('rechnungen', 'empfaenger_id')
    op.drop_column('energieeffizienzmassnahmen', 'created_at')
    # ### end Alembic commands ###