"""Add new changes

Revision ID: ed9785273900
Revises: 1d061519fbff
Create Date: 2024-01-21 10:51:21.754374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed9785273900'
down_revision: Union[str, None] = '1d061519fbff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rechnungen', 'rechnungsbetrag',
               existing_type=sa.NUMERIC(precision=10, scale=3),
               type_=sa.Numeric(precision=11, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rechnungen', 'rechnungsbetrag',
               existing_type=sa.Numeric(precision=11, scale=3),
               type_=sa.NUMERIC(precision=10, scale=3),
               existing_nullable=True)
    # ### end Alembic commands ###